### ISSUE TITLE
problem with text post with pic

### ISSUE THREAD

**Issue by alyak** [alyak/tcqpBot#1]
why it no work?
am dum

getquote = 'http://api.tinychat.com/scenefag.xml'
		rquote = re.compile(r'<pic>.*?</pic>')
		qdata = opener.open(getquote).read()
		qpick = rquote.findall(qdata)
		pic = re.sub(r'<[^>]*?>', '', unicode(qpick[0]))
		ohai = '*Say cheese!* ' + pic

it doesnt say "Say cheese!" first before url, just posts url.

**Comment by norwack** [comment]
Try to use xml.dom.minidom instead, (See here)[https://github.com/di0de/Tinychat_Scanner/blob/master/tinychat.py#L30]
